---
title: "Concordance Data Summary as of 2022-12-30"
output: 
  word_document:
    reference_docx: template.docx
    toc: TRUE
    toc_depth: 2
params:
  summarizingFunctions: Code/dataChecking/01_dataSummarizer.R
  summaryLayout: Code/reportRender/dataSummaryReportOutline.csv
---

# Summary

-   Summary of selected variables found in the Concordance Study for cleaning of data downloaded the 30 of December 2022.

```{r setup and establish connections, include=FALSE}



knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

source(params$summarizingFunctions)

reportRows <- c(3:10,24,25:26,30,59,60:70,87:90,91:101,113:143,169:202,215:220)

dataSummaryOutline <- read_csv(params$summaryLayout) %>% 
  slice(reportRows)

```

```{r creating summary structure}

dataSummaryOutline %<>%
  left_join(dataDict %>% select(varnm,rep,source,expandedVarnm,myLabel,shortcats,tp)) %>% 
  mutate(subsection=if_else(subsection==varnm,myLabel,subsection)) %>% 
  # select(myLabel) %>% 
  mutate(dataRows=if_else(is.na(rep),'',source),
         varnm=expandedVarnm) %>% 
  select(-rep,-source,-expandedVarnm) %>% 
  unnest_longer(varnm) %>% 
  group_by(section,subsection) %>% 
  summarise(ord=first(ord),
            varnm=list(varnm),
            dataRows=first(dataRows),
            tp=list(tp),
            shortcats=list(shortcats),
            myLabel=list(myLabel),
            graphicStyle=first(graphicStyle),
            graphic=first(graphic),
            .groups = 'drop') %>% 
  arrange(ord) %>% 
  relocate(ord,.before = 1) %>% 
  mutate(graphicData=map2(varnm,dataRows,~getData(data,.x,.y))) %>% 
  mutate(graphicData=pmap(list(graphicData,tp,graphicStyle,graphic),~cutData(..1,..2,..3,..4))) 

```



```{r Document Creation, results='asis'}



subKnit <- function(knitSection,knitSub){
  knitr::knit_child(text = c(
    '## `r knitSub`',
    '',
    '```{r}',
    'figure <- dataSummaryOutline %>% 
    filter(subsection==knitSub,section==knitSection)%$%
    pmap(list(graphicData,graphicStyle,graphic,tp,subsection),~figureGen(..1,..2,..3,..4,..5))',
    '',
    'figure[[1]]',
    '```',
    ''
  ), envir = environment(), quiet = TRUE)
}

sectionKnit <- function(knitSection, knitSub){
  # knitr::knit_child(param$knitChildFile, envir = environment(), quiet = TRUE)
  knitr::knit_child(text = c(
    '# `r knitSection`',
    '',
    '```{r, results="asis"}',
    'sectionRes <- knitSub %>%
    map(~subKnit(knitSection,.x))\n',
    'cat(unlist(sectionRes), sep = "\n")',
    '```',
    ''
  ), envir = environment(), quiet = TRUE) %>% 
    return()
}






res <- dataSummaryOutline %>% 
  filter(ord%in%c(3,87,90,215,217)) %>% 
  group_by(section) %>% 
  summarise(subsection=list(subsection),
            ord=first(ord)) %>% 
  arrange(ord)%$% 
  map2(section,subsection,~sectionKnit(.x,.y))
  
cat(unlist(res), sep = '\n')

```
